### ISSUE TITLE
Cannot get Console working

### ISSUE THREAD

**Issue by walprecht** [erlide/erlide#212]
Hello,

I am having a hard time to get the Console tab in ERLIDE working.

My setup is:
- OS: Win7 64-Bit
- JDK/JRE: 8.0.40 64-Bit
- Erl/OTP 17, Eshell V6.3
- Eclipse Juno 64-Bit Build id: 20130225-0426 (I tried with Luna - isn't working either)

When I run a simple Hello World program:
- The Eshell prompt is printed
- code completion in the input section works
but
- I cannot start any program. Seems that the communication between Eclipse and backend is disturbed.

Am I using a not supported SW-configuration?
Which one should be used?

Thanks in advance!

**Comment by vladdu** [comment]
It should work.

Is any error shown? Look also in the <workspace>/.metadata/.log file if there are any error messages that seem related.

**Comment by walprecht** [comment]
Thanks a lot! Looking in the log file showed that for some reason an old 32-Bit JRE was used and some strange class not found errors appeared. After I did a fresh Eclipse-Install (Kepler) it is working now. As far as I have seen ERLIDE is an excellent tool. I'd wish there would be something like that for Ocaml.

**Comment by vladdu** [comment]
Great! Please let me know if there's anything else.
