### ISSUE TITLE
Couldn't able to run erlide in Eclipse, throws an error

### ISSUE THREAD

**Issue by KamalakannanPE** [erlide/erlide#217]
I downloaded and installed **Eclipse Juna** from the Eclipse website. Installed Erlang/OTP R17 through **homebrew**. I didn't modify any settings in Erlang. But after I installed the plugin in Eclipse, "Configured erlang couldn't be started and erlide can't work" is popping up. 

**Note:** In terminal I could able to work with Erlang still.

![erlide_error](https://cloud.githubusercontent.com/assets/7580927/6915749/6001edac-d7b4-11e4-8d27-2cd914493ca9.png)

OS: Mac OSX 10.10 Yosemite

**Comment by vladdu** [comment]
Please check the "Troubleshooting" page on the erlang preferences. My guess is that your host name is ending with ".local" which confuses Erlang. To solve this you can rename your machine to something without dots or dashes, possibly adding that name to /etc/hosts. If that doesn't solve it, please send some more details.

**Comment by KamalakannanPE** [comment]
Thank you so much ! That worked .. :)

**Comment by dramalingaiah** [comment]
I downloaded the Eclipse Version: 2022-09 (4.25.0) and installed the Erlang plugins from [https://download.erlide.org/update/](url) but I am not able to even open Erlang project.
I get this error as soon as I open eclipse:
<img width="639" alt="image" src="https://user-images.githubusercontent.com/22264937/200025826-26657645-5c3b-4f27-8203-a68a5b0f4370.png">

I have updated the runtime settings to point to the correct erlang installation path. I am not sure why I am getting this error. I have spent hours trying to fix it by re-installing and trying all different options described but none of it works

Here is what I get in erlide.log
<img width="642" alt="image" src="https://user-images.githubusercontent.com/22264937/200026904-32a86486-b448-4eb9-a8d6-dd72c896dd09.png">

Thanks for your help in advance,
DR

**Comment by vladdu** [comment]
Please open a new ticket! This one is from 2015. 

What does the "troubleshooting" page in the preferences say? Unfortunately, erlide does not work with Erlang v25 and newer.

**Comment by dramalingaiah** [comment]
<img width="519" alt="image" src="https://user-images.githubusercontent.com/22264937/200028398-9295720c-5df4-477d-9deb-c063c3c3ea26.png">

**Comment by vladdu** [comment]
Is Erlang version 25?

**Comment by dramalingaiah** [comment]
Yes, 25.1.1

**Comment by vladdu** [comment]
Then it doesn't work, I am sorry about that. I am no longer maintaining the project and nobody else took over. Erlang 25 can no longer load beam files from older versions. 

I will try to check with the OTP team if something can be done about it.

Any v24 or older should work.

**Comment by dramalingaiah** [comment]
OK ,thank you so much for your time . I will try that and let you know if it works

**Comment by dramalingaiah** [comment]
It worked with an older version . I downloaded erlang 22 

Thanks you so much :)
