### ISSUE TITLE
unable to build erlide

### ISSUE THREAD

**Issue by martinpritchard** [erlide/erlide#225]
I'm trying to build erlide pu, as per wiki documentation 'building and distributing'.  I've installed Buckminster, jruby, rake, etc.  When I right click on org.erlide.site and select Buckminster->Invoke Action...->site.p2 (properties file org.erlide.site/buckminster.properties) I get a a NPE, something I'm missing?:

```
java.lang.NullPointerException
        at java.util.Hashtable.put(Hashtable.java:459)
        at org.apache.tools.ant.PropertyHelper.setUserProperty(PropertyHelper.java:750)
        at org.apache.tools.ant.Project.setUserProperty(Project.java:563)
        at org.eclipse.ant.internal.core.ant.InternalAntRunner.setProperties(InternalAntRunner.java:267)
        at org.eclipse.ant.internal.core.ant.InternalAntRunner.run(InternalAntRunner.java:632)
        at org.eclipse.ant.internal.core.ant.InternalAntRunner.run(InternalAntRunner.java:525)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.eclipse.buckminster.ant.AntRunner.run(AntRunner.java:318)
        at org.eclipse.buckminster.ant.actor.AntActor.internalPerform(AntActor.java:254)
        at org.eclipse.buckminster.core.actor.AbstractActor.perform(AbstractActor.java:195)
        at org.eclipse.buckminster.core.internal.actor.PerformManager$DirectActionInvocation.execute(PerformManager.java:143)
        at org.eclipse.buckminster.core.internal.actor.PerformManager.internalPerform(PerformManager.java:454)
        at org.eclipse.buckminster.core.internal.actor.PerformManager.perform(PerformManager.java:293)
        at org.eclipse.buckminster.core.internal.actor.PerformManager.perform(PerformManager.java:305)
        at org.eclipse.buckminster.ui.InvokeActionJob.runInWorkspace(InvokeActionJob.java:67)
        at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:38)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
```

**Comment by vladdu** [comment]
I think it's the same problem as https://bugs.eclipse.org/bugs/show_bug.cgi?id=445963, please try the solution suggested there.

**Comment by martinpritchard** [comment]
Thanks! As suggested in the bug, I've added the following to org.erlide.site/buckminster.properties (should this be part of the file by default? If not, it would sit quite nicely on the wiki)

```
osgi.user.area=${user.home}
osgi.user.area.default=${user.home}
osgi.configuration.area.default=<eclipse install location>
```

And it doesn't immediately explode - I get a little further, after about a minute of building, I get an include lib eunit error.  I'm guessing that I must be missing some other configuration:

```
!ENTRY org.eclipse.buckminster.core 4 293 2015-06-22 21:45:33.329
!MESSAGE can't find include lib "eunit/include/eunit.hrl"
```
I have erlang R16B03 installed.  Your help appreciated.

**Comment by vladdu** [comment]
I'm not sure where that message comes from. Could you please mail me the whole log?

Do you really need to get a CLI build working? Because the build can be done from Eclipse too, with a bit less troubles (but also a bit more manual intervention).

**Comment by martinpritchard** [comment]
I'm building from eclipse - ```can't find include lib "eunit/include/eunit.hrl"``` is displayed in a dialog box, and also printed to <eclipse workspace>/.metadata/.log, following right click on org.erlide.site and select Buckminster->Invoke Action...->site.p2 (properties file org.erlide.site/buckminster.properties).  

Here's the full log from around the time of the buckminster action run:
```
!ENTRY org.eclipse.ui 4 4 2015-06-22 21:43:32.446
!MESSAGE Plug-in 'org.eclipse.m2e.core.ui' contributed an invalid Menu Extension (Path: 'org.eclipse.ui.projectConfigure' is invalid): org.eclipse.m2e.enableNatureActio
n

!ENTRY org.eclipse.ui 4 4 2015-06-22 21:43:32.447
!MESSAGE Plug-in 'org.eclipse.wst.jsdt.ui' contributed an invalid Menu Extension (Path: 'org.eclipse.ui.projectConfigure' is invalid): org.eclipse.wst.jsdt.internal.web.ui.convertProjects

!ENTRY org.eclipse.ui 4 4 2015-06-22 21:43:32.448
!MESSAGE Plug-in 'org.eclipse.xtext.ui.shared' contributed an invalid Menu Extension (Path: 'org.eclipse.ui.projectConfigure' is invalid): org.eclipse.xtext.builder.action.AddXtextNatureAction

!ENTRY org.eclipse.ui 4 4 2015-06-22 21:43:32.448
!MESSAGE Plug-in 'org.erlide.ui' contributed an invalid Menu Extension (Path: 'org.eclipse.ui.projectConfigure' is invalid): org.erlide.ui.AddNatureAction

!ENTRY org.eclipse.ui 4 4 2015-06-22 21:43:32.711
!MESSAGE Plug-in 'org.eclipse.m2e.core.ui' contributed an invalid Menu Extension (Path: 'org.eclipse.ui.projectConfigure' is invalid): org.eclipse.m2e.enableNatureAction

!ENTRY org.eclipse.ui 4 4 2015-06-22 21:43:32.711
!MESSAGE Plug-in 'org.eclipse.wst.jsdt.ui' contributed an invalid Menu Extension (Path: 'org.eclipse.ui.projectConfigure' is invalid): org.eclipse.wst.jsdt.internal.web.ui.convertProjects

!ENTRY org.eclipse.ui 4 4 2015-06-22 21:43:32.712
!MESSAGE Plug-in 'org.eclipse.xtext.ui.shared' contributed an invalid Menu Extension (Path: 'org.eclipse.ui.projectConfigure' is invalid): org.eclipse.xtext.builder.action.AddXtextNatureAction

!ENTRY org.eclipse.ui 4 4 2015-06-22 21:43:32.712
!MESSAGE Plug-in 'org.erlide.ui' contributed an invalid Menu Extension (Path: 'org.eclipse.ui.projectConfigure' is invalid): org.erlide.ui.AddNatureAction

!ENTRY org.eclipse.buckminster.core 4 293 2015-06-22 21:45:33.329
!MESSAGE can't find include lib "eunit/include/eunit.hrl"
```

**Comment by vladdu** [comment]
That's weird... I never saw Buckminster messages in a dialog. 

What do you get in the buckminster log? There should be a bunch of lines like below, what are the last ones?

[start org.erlide.licenses:eclipse.feature$1.0.0.qualifier#manifest]
[end org.erlide.licenses:eclipse.feature$1.0.0.qualifier#manifest]
[start org.erlide.libs:osgi.bundle$1.15.0.qualifier#eclipse.build]
[end org.erlide.libs:osgi.bundle$1.15.0.qualifier#eclipse.build]

**Comment by martinpritchard** [comment]
I have enabled debug logging in Window/Preferences/Buckminster and have the following (grepping MESSAGE and ENTRY, there is lots of other output)

```
!MESSAGE [start org.erlide.cover.api:osgi.bundle$0.20.7.qualifier#eclipse.build]
!ENTRY org.eclipse.buckminster.core 1 293 2015-06-23 22:01:43.218
!MESSAGE [end org.erlide.cover.api:osgi.bundle$0.20.7.qualifier#eclipse.build]
!ENTRY org.eclipse.buckminster.core 0 293 2015-06-23 22:01:43.223
!MESSAGE init actor: eclipse.build[org.erlide.cover.core:osgi.bundle$0.2.24.qualifier#eclipse.build]
!ENTRY org.eclipse.buckminster.core 1 293 2015-06-23 22:01:43.226
!MESSAGE [start org.erlide.cover.core:osgi.bundle$0.2.24.qualifier#eclipse.build]
!ENTRY org.eclipse.buckminster.core 1 293 2015-06-23 22:01:43.255
!MESSAGE [end org.erlide.cover.core:osgi.bundle$0.2.24.qualifier#eclipse.build]
!ENTRY org.eclipse.buckminster.core 0 293 2015-06-23 22:01:43.257
!MESSAGE init actor: copyTargetFragments[org.erlide.cover.core:osgi.bundle$0.2.24.qualifier#target.fragments]
!ENTRY org.eclipse.buckminster.core 0 293 2015-06-23 22:01:43.271
!MESSAGE Action org.erlide.cover.core:osgi.bundle$0.2.24.qualifier#target.fragments using 'up to date' policy ACTOR: Product is up to date
!ENTRY org.eclipse.buckminster.core 0 293 2015-06-23 22:01:43.275
!MESSAGE Action org.erlide.cover.core:osgi.bundle$0.2.24.qualifier#manifest using 'up to date' policy DEFAULT: Product is up to date
!ENTRY org.eclipse.buckminster.core 0 293 2015-06-23 22:01:43.283
!MESSAGE Action org.erlide.cover.core:osgi.bundle$0.2.24.qualifier#bundle.jar using 'up to date' policy COUNT: Product is up to date
!ENTRY org.eclipse.buckminster.core 0 293 2015-06-23 22:01:43.291
!MESSAGE init actor: eclipse.build[org.erlide.cover.erlang:osgi.bundle$0.2.10.qualifier#eclipse.build]
!ENTRY org.eclipse.buckminster.core 1 293 2015-06-23 22:01:43.295
!MESSAGE [start org.erlide.cover.erlang:osgi.bundle$0.2.10.qualifier#eclipse.build]
!ENTRY org.eclipse.buckminster.core 4 293 2015-06-23 22:01:43.325
!MESSAGE can't find include lib "eunit/include/eunit.hrl"
```

**Comment by vladdu** [comment]
Ok, I learned something, setting the right buckminster preferences shows problems in a dialog.

I get a completely different problem (I don't run Buckminster from Eclipse here, so I think it's a configuration issue). 

What if you remove the sdk and optional gategories from build.properties? Maybe it has something to do with the cover plugin, since it's the one listed just before the error.

**Comment by martinpritchard** [comment]
Right, I've made some progress. Turns out that on linux mint, the apt-get install erlang will install just the runtime, and eunit doesn't ship with that, hence my problem.  Following a full erlang install and registering this with the IDE, the Buckminster build works.  Great!

My next problem is that I don't get how I actually deploy the newly built plugin to eclipse?  Really, at this stage I'm just interested in how I actually test any changes that I make in the IDE.  I can see lots of output in ~/tmp/erlide.site, but the docs mention  ```~/erlide_tools/target.platform```, which I don't seem to have.

**Comment by vladdu** [comment]
Aha, I should have thought about the incomplete erlang installation, now I remember I had other reports about that (with different symptoms).

The erlide_tools stuff is related to how things are set up on the build server, where I want all the needed tools with the right versions to be available in a single place, instead of relying on them being installed system-wide. You don't need to recreate that setting unless you like a good challenge :-)

The resulting update site should be in ~/tmp/erlide.site/org.erlide.site_1.0.0_something/site.p2 (or something like that, just do a find for "site.p2"). You can point Eclipse at that location (as a local update site) and install from there.

I may be stating the obvious, but you do know that you don't need to do all of this just to test your code, right? You can just create a launch configuration in Eclipse that includes the erlide projects and "Run" or "Debug" it. The whole Buckminster thing is for building on Jenkins and running the tests automatically. Actually, there is a use case where it is needed: if you need to use your changes  in order to be able to work on erlide itself.

**Comment by martinpritchard** [comment]
Well thats a bit more like it.  I didn't realise you could launch that way, all part of the learning curve!  Thanks for your help.

For those unfamiliar, its Run --> Run Configurations... --> Right click Eclipse Application, New, Run.  A new eclipse instance runs with your changes.

This is relatively straight-forward, but it does seem a bit long-winded to run up a fresh eclipse instance for each code change - is there a way to load code changes more quickly, or would something like JRebel need to be used?

**Comment by vladdu** [comment]
When running in debug mode, some changes to the Java code will get reloaded without requiring a restart. JRebel would help for more cases, yes. 

Unfortunately, it is a bit tricky to get the reloading working for the Erlang code, You have to launch an Erlang backend using the node name that is used internally by the debugged Eclipse, which you have to find from the logs. Then the Erlang code will get reloaded on save too (but changes involving persistent state might make things crash)

Please let me know if that information is not clear enough.

**Comment by martinpritchard** [comment]
Ok, thanks vlad. I'm up and running now so that's great. I'll see how I get on with hot code loading.
