### ISSUE TITLE
There is no way to securely download the plugin

### ISSUE THREAD

**Issue by magicgoose** [erlide/erlide#228]
The update site is http-only (no https), *and* the content is unsigned. That means, a man in the middle can easily replace some executable content with malicious code and this cannot be detected. Please, fix this ASAP, because it's impossible to install the plugin now without a huge risk.

![screen shot 2015-06-24 at 10 12 12 am](https://cloud.githubusercontent.com/assets/1442206/8324471/978d0c4c-1a59-11e5-8f35-b038c30c75ae.png)

**Comment by vladdu** [comment]
Unfortunately, I don't have the means to buy a code-signing certificate or a SSL certificate from a trusted authority. Do you think that a self-signed certificate would help reduce the risk?

For the update site, I suppose I could find a reasonably cheap (maybe even free) host that offers https, but it is still possible that someone else updated the code...

**Comment by magicgoose** [comment]
> Do you think that a self-signed certificate would help reduce the risk?

If the certificate fingerprint can be checked against a known valid value, which can be retrieved from a secure location (GitHub for example), then yes, it should. But I am not sure Eclipse will allow to check it prior to finishing install.

Alternatively, you can distribute the plugin as one zip file, and host it on GitHub (releases section is suitable for this), or host its checksums on GitHub. This will make install a bit less easy, but it will leave no possibility to tamper with the code for a third party.

**Comment by vladdu** [comment]
> If the certificate fingerprint can be checked against a known valid value, which can be retrieved from a secure location (GitHub for example), then yes, it should. But I am not sure Eclipse will allow to check it prior to finishing install.

I think one would have to check the fingerprint manually.

> Alternatively, you can distribute the plugin as one zip file, and host it on GitHub (releases section is suitable for this)

That is something that I can do without a lot of effort. I already have the zip file, so I'll check the GitHub API to having it uploaded by the build process.

**Comment by magicgoose** [comment]
That's great :+1:

**Comment by vladdu** [comment]
I just uploaded the zipped update site to the release, and I am working on a script to do that in the future.

Thanks for getting me do that! :smile:

**Comment by vladdu** [comment]
Added build task to upload zip to github
