### ISSUE TITLE
epp error, unable to build automatically

### ISSUE THREAD

**Issue by giocasu** [erlide/erlide#229]
Hi,
after updating to the new erlang OTP18 the plugin seems unable to autobuild a module if a macro is invoked in the code:
Description	Resource	Path	Location	Type
internal error in parse_module;
crash reason: {case_clause,{'EXIT',{undef,[{erl_scan,location,[{var,13,'Baz'}],[]},
                             {epp,expand_macros,5,
                                  [{file,"epp.erl"},{line,1196}]},
                             {epp,expand_macros,2,
                                  [{file,"epp.erl"},{line,1271}]},
                             {epp,scan_toks,3,
                                  [{file,"epp.erl"},{line,789}]}]}}}

  in function  epp:scan_toks/3 (epp.erl, line 789)	foo.erl	
line 0	Erlang Problems

(it happens with predefined macros too)
Through the console it can be built correctly though.

Regards,
Giovanni

**Comment by vladdu** [comment]
Thanks for reporting that, I'll get to it right away!

**Comment by vladdu** [comment]
Could you please give a try to the latest nightly build? http://download.erlide.org/update/nightly

**Comment by giocasu** [comment]
Hi, 
"You don't have permission to access /update/nightly/ on this server." :)

G.

**Comment by vladdu** [comment]
In Eclipse, go to "Help->Install new software" and use that URL in the dialog.

**Comment by giocasu** [comment]
Hi,
the macro expansions problem is gone, but now the console  seems broken: pressing enter after a well-formed command does nothing.

G.

**Comment by vladdu** [comment]
Ok, thanks, I'll look at that.

**Comment by vladdu** [comment]
Fixed, please try the latest nightly build.

**Comment by giocasu** [comment]
Now works fine, thanks!
