### ISSUE TITLE
Cannot run a module with a dash in its name

### ISSUE THREAD

**Issue by erindt** [erlide/erlide#231]
Hello,

When starting my work at an existing Erlang project, I tried to run/debug a test module and I got a message:
   exception error: undefined function tool:main/1

I suspect there could be a problem with a dash in the module name, which happens to be "aqe-tool". It does not matter whether I launch the aqe-tool:main(...) function directly or indirectly via another module.

Could you comment, please? Note I cannot easily rename the module as it is a part of a code base shared with a number of other engineers.

---------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------------

eclipse.buildId=4.4.2.M20150204-1700
java.version=1.8.0_45
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.java.product -keyring /Users/ert/.eclipse_keyring -showlocation
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -product org.eclipse.epp.package.java.product -keyring /Users/ert/.eclipse_keyring -showlocation
!ENTRY org.eclipse.core.net 1 0 2015-07-16 16:04:44.052
!MESSAGE System property http.nonProxyHosts has been set to local|*.local|169.254/16|*.169.254/16 by an external source. This value will be overwritten using the values from the preferences
!ENTRY org.erlide.core 1 0 2015-07-16 16:04:46.186
!MESSAGE Erlide log is in /Users/ert/workspace/eclipse
!ENTRY org.erlide.core 1 0 2015-07-16 16:04:46.201
!MESSAGE *** starting Erlide v0.29.12.201507101554 (core=0.24.13.201507101554) (model api=0.24.12.201507101554) *** (UTF-8) ui
!ENTRY org.eclipse.text 4 2 2015-07-16 16:08:19.567
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.text".
...
...
==================================

16:04:46,196 I: (ErlangCore.java:64) : Starting CORE Thread[main,6,main]
16:04:46,201 I: (ErlangCore.java:79) : *** starting Erlide v0.29.12.201507101554 (core=0.24.13.201507101554) (model api=0.24.12.201507101554) *** (UTF-8) ui
16:04:46,202 I: (ErlangCore.java:86) : Started CORE
16:04:46,203 F: (ErlangPlugin.java:88) : Core started
16:04:46,496 F: (ErlangHostnameRetriever.java:40) : Test long hostname: Eduards-MacBook-Pro.local
16:04:46,753 F: (ErlangHostnameRetriever.java:40) : Test short hostname: Eduards-MacBook-Pro
16:04:46,780 F: (HostnameUtils.java:74) : Detected:: Eduards-MacBook-Pro && Eduards-MacBook-Pro.local
16:04:46,796 F: (BackendActivator.java:25) : Backend plugin started
16:04:46,800 F: (BackendFactory.java:42) : Create ide backend 17.5.0
16:04:46,800 F: (BackendFactory.java:56) : Create backend 7c1af_ert_2e8b4e_erlide
16:04:46,839 F: (OtpNodeProxy.java:301) : Runtime 7c1af_ert_2e8b4e_erlide@Eduards-MacBook-Pro.local starting
16:04:46,839 F: (OtpNodeProxy.java:419) : START node :> [/usr/local/lib/erlang/bin/erl, -name, 7c1af_ert_2e8b4e_erlide@Eduards-MacBook-Pro.local, -setcookie, erlide] *** /Users/ert/workspace/eclipse
16:04:46,860 F: (OtpNodeProxy.java:212) : 7c1af_ert_2e8b4e_erlide@Eduards-MacBook-Pro.local: waiting connection to peer... 
16:04:47,271 F: (OtpNodeProxy.java:219) : connected!
16:04:47,382 F: (OtpNodeProxy.java:306) : Runtime 7c1af_ert_2e8b4e_erlide@Eduards-MacBook-Pro.local running
16:04:47,474 F: (LogEventHandler.java:27) : info: {"Monitoring java node",'jerlide_72e8b86@Eduards-MacBook-Pro.local'}
16:04:47,475 F: (LogEventHandler.java:27) : info: {"Start monitor process: ",10000000,50000000}
16:04:47,906 F: (ModelActivator.java:30) : Started model api
16:04:47,929 I: (ErlideUIPlugin.java:130) : Starting UI Thread[main,6,main]
16:04:47,935 I: (ErlideUIPlugin.java:152) : Started UI
16:05:46,984 F: (BackendManager.java:90) : create execution backend erlide
16:05:46,985 F: (BackendFactory.java:56) : Create backend erlide
16:05:46,986 F: (OtpNodeProxy.java:301) : Runtime erlide@Eduards-MacBook-Pro.local starting
16:05:46,986 F: (OtpNodeProxy.java:419) : START node :> [/usr/local/lib/erlang/bin/erl, -name, erlide@Eduards-MacBook-Pro.local] *** /Users/ert/workspace/eclipse
16:05:46,992 F: (OtpNodeProxy.java:212) : erlide@Eduards-MacBook-Pro.local: waiting connection to peer... 
16:05:47,400 F: (OtpNodeProxy.java:219) : connected!
16:05:47,662 F: (ErlangDebugTarget.java:124) : debug started #Pid<erlide@Eduards-MacBook-Pro.local.73.0>
16:05:47,684 F: (ErlangDebugTarget.java:472) : interpret aqe_optimizer
16:05:47,749 F: (ErlangDebugTarget.java:472) : interpret aqe_optimizer_property
16:05:47,774 F: (ErlangDebugTarget.java:472) : interpret aqe_maql
16:05:47,811 F: (ErlangDebugTarget.java:472) : interpret aqe-tool
16:05:47,847 F: (ErlangDebugTarget.java:472) : interpret aqe_ldm
16:05:47,880 F: (ErlangDebugTarget.java:472) : interpret aqe_property
16:05:47,905 F: (ErlangDebugTarget.java:472) : interpret aqe_compattrs
16:05:47,935 F: (ErlangDebugTarget.java:472) : interpret aqe_regression
16:05:47,960 F: (ErlangDebugTarget.java:472) : interpret aqe_pdm
16:05:48,003 F: (ErlConsoleManager.java:50) : console ADDED to org.erlide.backend.api.BackendData@6d80d34c
16:05:48,015 F: (OtpNodeProxy.java:306) : Runtime erlide@Eduards-MacBook-Pro.local running
16:05:48,016 F: (LogEventHandler.java:27) : info: {"Monitoring java node",'jerlide_72f766f@Eduards-MacBook-Pro.local'}
16:05:48,017 F: (LogEventHandler.java:27) : info: {"Start monitor process: ",10000000,50000000}
16:05:48,051 F: (ErlangLaunchDelegate.java:111) : Started erts: erlide >> erlide
16:09:19,133 F: (BackendFactory.java:49) : Create build backend 17
16:09:19,133 F: (BackendFactory.java:56) : Create backend 17_7c1af_ert_32b31d
16:09:19,134 F: (OtpNodeProxy.java:301) : Runtime 17_7c1af_ert_32b31d@Eduards-MacBook-Pro.local starting
16:09:19,134 F: (OtpNodeProxy.java:419) : START node :> [/usr/local/lib/erlang/bin/erl, -name, 17_7c1af_ert_32b31d@Eduards-MacBook-Pro.local, -setcookie, erlide] *** /Users/ert/workspace/eclipse
16:09:19,137 F: (OtpNodeProxy.java:212) : 17_7c1af_ert_32b31d@Eduards-MacBook-Pro.local: waiting connection to peer... 
16:09:19,544 F: (OtpNodeProxy.java:219) : connected!
16:09:19,649 F: (OtpNodeProxy.java:306) : Runtime 17_7c1af_ert_32b31d@Eduards-MacBook-Pro.local running
16:09:19,731 F: (LogEventHandler.java:27) : info: {"Monitoring java node",'jerlide_732b321@Eduards-MacBook-Pro.local'}
16:09:19,732 F: (LogEventHandler.java:27) : info: {"Start monitor process: ",10000000,50000000}
16:09:20,376 F: (AbstractErlContentAssistProcessor.java:362) : no results
16:13:06,425 W: (OtpNodeProxy.java:280) : Runtime erlide@Eduards-MacBook-Pro.local crashed, exit code: 143.
16:14:00,163 F: (BackendManager.java:90) : create execution backend erlide
16:14:00,163 F: (BackendFactory.java:56) : Create backend erlide
16:14:00,164 F: (OtpNodeProxy.java:419) : START node :> [/usr/local/lib/erlang/bin/erl, -name, erlide@Eduards-MacBook-Pro.local] *** /Users/ert/workspace/eclipse
16:14:00,164 F: (OtpNodeProxy.java:301) : Runtime erlide@Eduards-MacBook-Pro.local starting
16:14:00,167 F: (OtpNodeProxy.java:212) : erlide@Eduards-MacBook-Pro.local: waiting connection to peer... 
16:14:00,577 F: (OtpNodeProxy.java:219) : connected!
16:14:00,842 F: (ErlangDebugTarget.java:124) : debug started #Pid<erlide@Eduards-MacBook-Pro.local.73.0>
16:14:00,868 F: (ErlangDebugTarget.java:472) : interpret aqe_optimizer
16:14:00,932 F: (ErlangDebugTarget.java:472) : interpret aqe_optimizer_property
16:14:00,960 F: (ErlangDebugTarget.java:472) : interpret aqe_maql
16:14:00,999 F: (ErlangDebugTarget.java:472) : interpret aqe-tool
16:14:01,036 F: (ErlangDebugTarget.java:472) : interpret aqe_ldm
16:14:01,068 F: (ErlangDebugTarget.java:472) : interpret aqe_property
16:14:01,095 F: (ErlangDebugTarget.java:472) : interpret aqe_compattrs
16:14:01,125 F: (ErlangDebugTarget.java:472) : interpret aqe_regression
16:14:01,149 F: (ErlangDebugTarget.java:472) : interpret aqe_pdm
16:14:01,183 F: (ErlConsoleManager.java:50) : console ADDED to org.erlide.backend.api.BackendData@5c384610
16:14:01,202 F: (OtpNodeProxy.java:306) : Runtime erlide@Eduards-MacBook-Pro.local running
16:14:01,203 F: (LogEventHandler.java:27) : info: {"Monitoring java node",'jerlide_736fce6@Eduards-MacBook-Pro.local'}
16:14:01,203 F: (LogEventHandler.java:27) : info: {"Start monitor process: ",10000000,50000000}
16:14:01,208 F: (ErlangLaunchDelegate.java:111) : Started erts: erlide >> erlide
16:14:12,710 F: (ErlTextHover.java:297) : otp doc {error,error}...
16:14:37,417 F: (AbstractErlContentAssistProcessor.java:362) : no results
16:15:11,665 F: (OtpNodeProxy.java:311) : Runtime erlide@Eduards-MacBook-Pro.local stopping
16:15:20,552 W: (OtpNodeProxy.java:280) : Runtime erlide@Eduards-MacBook-Pro.local crashed, exit code: 143.
16:16:01,715 F: (InternalBuilder.java:202) : Will compile 1 resource(s)
16:16:05,204 F: (ErlTextHover.java:297) : otp doc {error,error}...
16:16:10,834 F: (ErlParser.java:342) : unknown: {other,{{11,11,263},4},main,[{token,atom,11,263,4,main,"main",u,u}]}
16:16:11,944 F: (ErlParser.java:342) : unknown: {other,{{11,11,263},4},main,[{token,atom,11,263,4,main,"main",u,u}]}
16:16:13,180 F: (ErlParser.java:342) : unknown: {other,{{11,11,263},4},main,[{token,atom,11,263,4,main,"main",u,u},{token,')',11,268,1,u,")",u,u}]}
16:16:13,695 F: (ErlParser.java:342) : unknown: {other,{{11,11,263},4},main,[{token,atom,11,263,4,main,"main",u,u}]}
16:16:22,348 F: (AbstractErlContentAssistProcessor.java:362) : no results
16:16:43,032 F: (InternalBuilder.java:202) : Will compile 1 resource(s)
16:17:29,513 F: (BackendManager.java:90) : create execution backend erlide
16:17:29,513 F: (BackendFactory.java:56) : Create backend erlide
16:17:29,515 F: (OtpNodeProxy.java:301) : Runtime erlide@Eduards-MacBook-Pro.local starting
16:17:29,515 F: (OtpNodeProxy.java:419) : START node :> [/usr/local/lib/erlang/bin/erl, -name, erlide@Eduards-MacBook-Pro.local] *** /Users/ert/workspace/eclipse
16:17:29,519 F: (OtpNodeProxy.java:212) : erlide@Eduards-MacBook-Pro.local: waiting connection to peer... 
16:17:29,930 F: (OtpNodeProxy.java:219) : connected!
16:17:30,171 F: (ErlangDebugTarget.java:124) : debug started #Pid<erlide@Eduards-MacBook-Pro.local.73.0>
16:17:30,194 F: (ErlangDebugTarget.java:472) : interpret aqe_optimizer
16:17:30,258 F: (ErlangDebugTarget.java:472) : interpret aqe_optimizer_property
16:17:30,290 F: (ErlangDebugTarget.java:472) : interpret aqe_maql
16:17:30,325 F: (ErlangDebugTarget.java:472) : interpret aqe-tool
16:17:30,364 F: (ErlangDebugTarget.java:472) : interpret aqe_ldm
16:17:30,395 F: (ErlangDebugTarget.java:472) : interpret aqe_property
16:17:30,424 F: (ErlangDebugTarget.java:472) : interpret aqe_compattrs
16:17:30,454 F: (ErlangDebugTarget.java:472) : interpret aqe_regression
16:17:30,479 F: (ErlangDebugTarget.java:472) : interpret aqe_pdm
16:17:30,533 F: (OtpNodeProxy.java:306) : Runtime erlide@Eduards-MacBook-Pro.local running
16:17:30,533 F: (LogEventHandler.java:27) : info: {"Monitoring java node",'jerlide_73a2eae@Eduards-MacBook-Pro.local'}
16:17:30,534 F: (LogEventHandler.java:27) : info: {"Start monitor process: ",10000000,50000000}
16:17:30,536 F: (ErlConsoleManager.java:50) : console ADDED to org.erlide.backend.api.BackendData@74659e1
16:17:30,565 F: (ErlangLaunchDelegate.java:111) : Started erts: erlide >> erlide
16:21:51,482 F: (ErlangSearchPage.java:620) : searchPage(open) OpenResult {}
16:36:40,699 I: (ReportPreferencePage.java:187) : 
++++++++++++++++++++++
System information could not be retrieved (node not monitored)...

**Comment by vladdu** [comment]
To make sure that I understood correctly: you have module aqe-tool.erl and have started the project from erlide and in the console you want to call then main function. Is that correct? 

That works for me. Did you put the module name in quotes -- 'aqe-tool':main(...) ? From the error message it feels that that would be the most probable cause.

**Comment by erindt** [comment]
You're correct, I found it myself in parallel. As a newbie to Erlang, I did not realise that a module name is an atom actually and, hence, it must be written quoted when it contains a dash.
Thanks anyway!
