### ISSUE TITLE
Debug Configurations Node name 

### ISSUE THREAD

**Issue by martinpritchard** [erlide/erlide#233]
Is there a reason why we can't specify the Node name fully on the Debug Configurations dialog?  It is currently restricted to a greyed out ```@localhost``` or ```@127.0.0.1``` depending on long or short names.  This effectively disables remote debugging, but also I'm having trouble getting a local debugging session up and running because my node is wanting the result of the ```hostname``` command.  It would be good if we could just use the result of node() from the node that we want to connect to and paste it in.

**Comment by vladdu** [comment]
It may be a bit unclear, but if you keep writing "..@whatever.com" in the field, that will override the default values of localhost or 127.0.0.1.

If you have suggestions about how to explain it better on the dialog, please let me know.

**Comment by martinpritchard** [comment]
Ah I see,  I'll give that a try.  Maybe it would be better without the @localhost, etc.  Could erlide derive whether short or long names are to be used based on whether a fully qualified domain name is specified, thus simplifying the UI?

**Comment by vladdu** [comment]
The long/short choice is irrelevant if you specify a host name, it gets the right value and is grayed out. It is useful when choosing between the two default host names (if /etc/hosts or similar is set up properly, one gets real names instead of localhost and 127.0.0.1)

**Comment by martinpritchard** [comment]
I think the UI would be ok with just 2 input boxes, Node name and Cookie (the other parts to the UI confused me).

**Comment by vladdu** [comment]
I see, I'll try to hide options that are irrelevent behind an "advanced" tab. Thanks for the feedback!

**Comment by vladdu** [comment]
By "the other parts of the UI" do you mean everything else, or just the long/short name toggle and the not explained way to input the host name?

**Comment by martinpritchard** [comment]
Yes, that's correct.

**Comment by vladdu** [comment]
What's correct? :smile: "else" or "just"?

**Comment by martinpritchard** [comment]
Sorry - just the long/short name toggle and the not explained way to input the host name
