### ISSUE TITLE
erlide-proj compile error with erlang 18 - set() and dict()

### ISSUE THREAD

**Issue by frehberg** [erlide/erlide#248]
Compiling erlide-project with erlang 18 is causing erros like "type set() undefined" and "type dict() undefined" in the following file:

 org.erlide.kernel.tools/src/erlide_dialyze.erl

It seems this is due to changes in type-system of erlang 18

To solve the issue, replace dict() by dict:dict() and replace set() by set:set()

**Comment by frehberg** [comment]
Attached is the diff file with required changes for e18:

[erlide-e18-diff.txt](https://github.com/erlide/erlide/files/35223/erlide-e18-diff.txt)

**Comment by vladdu** [comment]
Thanks for the feedback!

I know this gives errors, but this code must be possible to run on all supported Erlang versions (R16+), where this change would give compile errors... The kernel.tools project specifies that it should be built with the R16 compiler, where that isn't an issue.

Currently, the only way to allow compiling with OTP 18 would be to create a parallel project, like for the debugger, but I would not be very happy to do that. 

Do you *really need* to compile with OTP 18?

**Comment by frehberg** [comment]
No, I don't need OTP 18, just for documentation purpose. I think I  can stay with OTP 16 for now.

**Comment by vladdu** [comment]
I'm closing this, as I think the question has been answered.
