### ISSUE TITLE
Erlang runtime is not save

### ISSUE THREAD

**Issue by masalinas** [erlide/erlide#256]
Erlide plugin inside Eclipe Mars on Ubuntu 12.04 not save the runtime configured throw Windows/Preferences inside Eclipse. I set this path: /usr/lib/erlang

![image](https://cloud.githubusercontent.com/assets/1216181/13460228/9487ea08-e079-11e5-87f0-db201d6d9a74.png)

And don't save this configuration so when start eclipse obtain an error telling me that I must to configure the erlang runtime.

Whats the problem?, is it a bug?

Regards

**Comment by vladdu** [comment]
Is your Erlang installed via apt-get? If yes, then that's the problem: the location must be the root of an OTP installation (so that we can find the libraries and the documentation). Best way is to install manually (with kerl it is easy) and use that location instead.

**Comment by masalinas** [comment]
Yes I installed throw apt-get and not manually, so I must to remove all the erlang packages installed and start again ;(

**Comment by vladdu** [comment]
That is a problem. I had some ideas about how to inform users about it, I'll try to actually implement it.
