### ISSUE TITLE
Module conflict in Update

### ISSUE THREAD

**Issue by gasserles** [erlide/erlide#262]
I installed the Erlang IDE in Eclipse Mars.2 (4.5.2), using the Erlide update site http://download.erlide.org/update . After a seemingly successful install, I immediately did an update (Help/Check for Updates -> install them). There was a problem with the updates, and Eclipse tried "Alternate methods". This failed with the details below. It seems there is some kind of module conflict. This report was constructed using Erlide's Preferences/Erlang/Report Problems item. This is possibly related to issue #252.

Erlang language tools IDE	0.30.0.201511031603

Cannot complete the install because of a conflicting dependency.
  Software being installed: Erlang language tools IDE 0.30.0.201511031603 (org.erlide.feature.group 0.30.0.201511031603)
  Software currently installed: Erlang headless support 0.29.13.201509181435 (org.erlide.headless.feature.group 0.29.13.201509181435)
  Only one of the following can be installed at once: 
    erlide - Erlang language tools 0.24.4.201511031603 (org.erlide.branding 0.24.4.201511031603)
    erlide - Erlang language tools 0.24.4.201509181435 (org.erlide.branding 0.24.4.201509181435)
  Cannot satisfy dependency:
    From: Erlang language tools IDE 0.30.0.201511031603 (org.erlide.feature.group 0.30.0.201511031603)
    To: org.erlide.branding [0.24.4.201511031603]
  Cannot satisfy dependency:
    From: Erlang headless support 0.29.13.201509181435 (org.erlide.headless.feature.group 0.29.13.201509181435)
    To: org.erlide.branding [0.24.4.201509181435]
gasserles@gmail.com

==================================

!SESSION 2016-03-27 14:35:09.737 -----------------------------------------------
eclipse.buildId=4.5.2.M20160212-1500
java.version=1.8.0_11
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.java.product -keyring /Users/gasser/.eclipse_keyring -showlocation
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -product org.eclipse.epp.package.java.product -keyring /Users/gasser/.eclipse_keyring -showlocation
!ENTRY org.eclipse.core.net 1 0 2016-03-27 14:35:16.989
!MESSAGE System property http.nonProxyHosts has been set to local|*.local|169.254/16|*.169.254/16 by an external source. This value will be overwritten using the values from the preferences
!ENTRY org.erlide.core 1 0 2016-03-27 14:35:18.350
!MESSAGE Erlide log is in /Users/gasser/Projects/EclipseWorkspaces/PapersMarsWorkspace
!ENTRY org.erlide.core 1 0 2016-03-27 14:35:18.397
!MESSAGE *** starting Erlide v0.29.13.201509181435 (core=0.24.13.201509181435) (model api=0.24.12.201509181435) *** (UTF-8) ui
!ENTRY org.eclipse.equinox.p2.operations 4 0 2016-03-28 13:17:29.807
!MESSAGE No remedy found
!ENTRY org.eclipse.equinox.p2.operations 4 0 2016-03-28 13:17:29.915
!MESSAGE Operation details
!SUBENTRY 1 org.eclipse.equinox.p2.director 4 10054 2016-03-28 13:17:29.915
!MESSAGE Cannot complete the install because of a conflicting dependency.
!SUBENTRY 2 org.eclipse.equinox.p2.director 4 0 2016-03-28 13:17:29.915
!MESSAGE Software being installed: Erlang language tools IDE 0.30.0.201511031603 (org.erlide.feature.group 0.30.0.201511031603)
!SUBENTRY 2 org.eclipse.equinox.p2.director 4 0 2016-03-28 13:17:29.915
!MESSAGE Software currently installed: Erlang headless support 0.29.13.201509181435 (org.erlide.headless.feature.group 0.29.13.201509181435)
!SUBENTRY 2 org.eclipse.equinox.p2.director 4 1 2016-03-28 13:17:29.915
!MESSAGE Only one of the following can be installed at once:
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2016-03-28 13:17:29.915
!MESSAGE erlide - Erlang language tools 0.24.4.201511031603 (org.erlide.branding 0.24.4.201511031603)
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2016-03-28 13:17:29.915
!MESSAGE erlide - Erlang language tools 0.24.4.201509181435 (org.erlide.branding 0.24.4.201509181435)
!SUBENTRY 2 org.eclipse.equinox.p2.director 4 1 2016-03-28 13:17:29.915
!MESSAGE Cannot satisfy dependency:
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2016-03-28 13:17:29.915
!MESSAGE From: Erlang language tools IDE 0.30.0.201511031603 (org.erlide.feature.group 0.30.0.201511031603)
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2016-03-28 13:17:29.915
!MESSAGE To: org.erlide.branding [0.24.4.201511031603]
!SUBENTRY 2 org.eclipse.equinox.p2.director 4 1 2016-03-28 13:17:29.915
!MESSAGE Cannot satisfy dependency:
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2016-03-28 13:17:29.915
!MESSAGE From: Erlang headless support 0.29.13.201509181435 (org.erlide.headless.feature.group 0.29.13.201509181435)
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2016-03-28 13:17:29.915
!MESSAGE To: org.erlide.branding [0.24.4.201509181435]
!ENTRY org.eclipse.equinox.p2.operations 4 0 2016-03-28 13:17:29.951
!MESSAGE Operation details
!SUBENTRY 1 org.eclipse.equinox.p2.director 4 10054 2016-03-28 13:17:29.951
!MESSAGE Cannot complete the install because of a conflicting dependency.
!SUBENTRY 2 org.eclipse.equinox.p2.director 4 0 2016-03-28 13:17:29.951
!MESSAGE Software being installed: Erlang language tools IDE 0.30.0.201511031603 (org.erlide.feature.group 0.30.0.201511031603)
!SUBENTRY 2 org.eclipse.equinox.p2.director 4 0 2016-03-28 13:17:29.951
!MESSAGE Software currently installed: Erlang headless support 0.29.13.201509181435 (org.erlide.headless.feature.group 0.29.13.201509181435)
!SUBENTRY 2 org.eclipse.equinox.p2.director 4 1 2016-03-28 13:17:29.951
!MESSAGE Only one of the following can be installed at once:
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2016-03-28 13:17:29.951
!MESSAGE erlide - Erlang language tools 0.24.4.201511031603 (org.erlide.branding 0.24.4.201511031603)
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2016-03-28 13:17:29.951
!MESSAGE erlide - Erlang language tools 0.24.4.201509181435 (org.erlide.branding 0.24.4.201509181435)
!SUBENTRY 2 org.eclipse.equinox.p2.director 4 1 2016-03-28 13:17:29.951
!MESSAGE Cannot satisfy dependency:
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2016-03-28 13:17:29.951
!MESSAGE From: Erlang language tools IDE 0.30.0.201511031603 (org.erlide.feature.group 0.30.0.201511031603)
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2016-03-28 13:17:29.951
!MESSAGE To: org.erlide.branding [0.24.4.201511031603]
!SUBENTRY 2 org.eclipse.equinox.p2.director 4 1 2016-03-28 13:17:29.951
!MESSAGE Cannot satisfy dependency:
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2016-03-28 13:17:29.951
!MESSAGE From: Erlang headless support 0.29.13.201509181435 (org.erlide.headless.feature.group 0.29.13.201509181435)
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2016-03-28 13:17:29.951
!MESSAGE To: org.erlide.branding [0.24.4.201509181435]
!ENTRY org.eclipse.equinox.p2.operations 4 0 2016-03-28 13:17:30.939
!MESSAGE Operation details
!SUBENTRY 1 org.eclipse.equinox.p2.director 4 10054 2016-03-28 13:17:30.939
!MESSAGE Cannot complete the install because of a conflicting dependency.
!SUBENTRY 2 org.eclipse.equinox.p2.director 4 0 2016-03-28 13:17:30.939
!MESSAGE Software being installed: Erlang language tools IDE 0.30.0.201511031603 (org.erlide.feature.group 0.30.0.201511031603)
!SUBENTRY 2 org.eclipse.equinox.p2.director 4 0 2016-03-28 13:17:30.939
!MESSAGE Software currently installed: Erlang headless support 0.29.13.201509181435 (org.erlide.headless.feature.group 0.29.13.201509181435)
!SUBENTRY 2 org.eclipse.equinox.p2.director 4 1 2016-03-28 13:17:30.940
!MESSAGE Only one of the following can be installed at once:
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2016-03-28 13:17:30.940
!MESSAGE erlide - Erlang language tools 0.24.4.201511031603 (org.erlide.branding 0.24.4.201511031603)
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2016-03-28 13:17:30.940
!MESSAGE erlide - Erlang language tools 0.24.4.201509181435 (org.erlide.branding 0.24.4.201509181435)
!SUBENTRY 2 org.eclipse.equinox.p2.director 4 1 2016-03-28 13:17:30.940
!MESSAGE Cannot satisfy dependency:
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2016-03-28 13:17:30.940
!MESSAGE From: Erlang language tools IDE 0.30.0.201511031603 (org.erlide.feature.group 0.30.0.201511031603)
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2016-03-28 13:17:30.940
!MESSAGE To: org.erlide.branding [0.24.4.201511031603]
!SUBENTRY 2 org.eclipse.equinox.p2.director 4 1 2016-03-28 13:17:30.940
!MESSAGE Cannot satisfy dependency:
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2016-03-28 13:17:30.940
!MESSAGE From: Erlang headless support 0.29.13.201509181435 (org.erlide.headless.feature.group 0.29.13.201509181435)
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2016-03-28 13:17:30.940
!MESSAGE To: org.erlide.branding [0.24.4.201509181435]
!ENTRY org.eclipse.equinox.p2.operations 4 0 2016-03-28 13:17:30.940
!MESSAGE Operation details
!SUBENTRY 1 org.eclipse.equinox.p2.director 4 10054 2016-03-28 13:17:30.940
!MESSAGE Cannot complete the install because of a conflicting dependency.
!SUBENTRY 2 org.eclipse.equinox.p2.director 4 0 2016-03-28 13:17:30.940
!MESSAGE Software being installed: Erlang language tools IDE 0.30.0.201511031603 (org.erlide.feature.group 0.30.0.201511031603)
!SUBENTRY 2 org.eclipse.equinox.p2.director 4 0 2016-03-28 13:17:30.940
!MESSAGE Software currently installed: Erlang headless support 0.29.13.201509181435 (org.erlide.headless.feature.group 0.29.13.201509181435)
!SUBENTRY 2 org.eclipse.equinox.p2.director 4 1 2016-03-28 13:17:30.940
!MESSAGE Only one of the following can be installed at once:
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2016-03-28 13:17:30.940
!MESSAGE erlide - Erlang language tools 0.24.4.201511031603 (org.erlide.branding 0.24.4.201511031603)
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2016-03-28 13:17:30.940
!MESSAGE erlide - Erlang language tools 0.24.4.201509181435 (org.erlide.branding 0.24.4.201509181435)
!SUBENTRY 2 org.eclipse.equinox.p2.director 4 1 2016-03-28 13:17:30.941
!MESSAGE Cannot satisfy dependency:
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2016-03-28 13:17:30.941
!MESSAGE From: Erlang language tools IDE 0.30.0.201511031603 (org.erlide.feature.group 0.30.0.201511031603)
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2016-03-28 13:17:30.941
!MESSAGE To: org.erlide.branding [0.24.4.201511031603]
!SUBENTRY 2 org.eclipse.equinox.p2.director 4 1 2016-03-28 13:17:30.941
!MESSAGE Cannot satisfy dependency:
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2016-03-28 13:17:30.941
!MESSAGE From: Erlang headless support 0.29.13.201509181435 (org.erlide.headless.feature.group 0.29.13.201509181435)
!SUBENTRY 3 org.eclipse.equinox.p2.director 4 0 2016-03-28 13:17:30.941
!MESSAGE To: org.erlide.branding [0.24.4.201509181435]

==================================

14:35:18,356 I: (ErlangCore.java:64) : Starting CORE Thread[main,6,main]
14:35:18,397 I: (ErlangCore.java:79) : *** starting Erlide v0.29.13.201509181435 (core=0.24.13.201509181435) (model api=0.24.12.201509181435) *** (UTF-8) ui
14:35:18,444 I: (ErlangCore.java:86) : Started CORE
14:35:18,444 F: (ErlangPlugin.java:88) : Core started
14:35:19,543 F: (ErlangHostnameRetriever.java:40) : Test long hostname: null
14:35:19,543 W: (ErlangHostnameRetriever.java:46) : Can't use null as long name
14:35:20,377 F: (ErlangHostnameRetriever.java:40) : Test long hostname: lis-02-gasser
14:35:21,399 W: (ErlangHostnameRetriever.java:46) : Can't use lis-02-gasser as long name
14:35:21,619 F: (ErlangHostnameRetriever.java:40) : Test short hostname: lis-02-gasser
14:35:21,627 F: (HostnameUtils.java:74) : Detected:: lis-02-gasser && null
14:35:21,638 F: (BackendActivator.java:25) : Backend plugin started
14:35:21,698 I: (ErlideUIPlugin.java:132) : Starting UI Thread[main,6,main]
14:35:21,714 F: (ModelActivator.java:19) : Starting Erlang model api
14:35:21,775 F: (BackendFactory.java:42) : Create ide backend 18.3.0
14:35:21,775 F: (BackendFactory.java:56) : Create backend 3caec_gasser_92d7ac_erlide
14:35:21,817 F: (OtpNodeProxy.java:419) : START node :> [/usr/local/lib/erlang/bin/erl, -sname, 3caec_gasser_92d7ac_erlide@lis-02-gasser, -setcookie, erlide] *** /Users/gasser/Projects/EclipseWorkspaces/PapersMarsWorkspace
14:35:21,818 F: (OtpNodeProxy.java:301) : Runtime 3caec_gasser_92d7ac_erlide@lis-02-gasser starting
14:35:21,831 F: (OtpNodeProxy.java:212) : 3caec_gasser_92d7ac_erlide@lis-02-gasser: waiting connection to peer... 
14:35:22,238 F: (OtpNodeProxy.java:219) : connected!
14:35:22,345 F: (OtpNodeProxy.java:306) : Runtime 3caec_gasser_92d7ac_erlide@lis-02-gasser running
14:35:22,431 F: (LogEventHandler.java:27) : info: {"Monitoring java node",'jerlide_992d7e2@lis-02-gasser'}
14:35:22,432 F: (LogEventHandler.java:27) : info: {"Start monitor process: ",10000000,50000000}
14:35:22,869 F: (ModelActivator.java:30) : Started model api
14:35:22,888 I: (ErlideUIPlugin.java:154) : Started UI
00:00:00,001 I: (ErlideUIPlugin.java:245) : *** Automatically cleaning caches ***
13:21:25,898 I: (ReportPreferencePage.java:187) : 
++++++++++++++++++++++
System information could not be retrieved (node not monitored)...

**Comment by vladdu** [comment]
I will look at it. If you uninstall the existing version, restart and install the new one, it should work ok. Please let me know if it doesn't.

**Comment by gasserles** [comment]
Thanks, Vlad. Please note: I used the Erlide update site for the original install, just minutes before I tried the "Check for updates" and hit the conflict; this was just a couple of days ago. I will try uninstalling and reinstalling Erlide, again from the update site - as you recommend. But it's not clear to me how would I get a "new one" version by using the update site, again.  - Les

**Comment by gasserles** [comment]
Followup: I uninstalled Erlide, then tried to re-install using the update site. I got the error below. Eclipse was going to try installing using an "alternate method" which appears to be by downgrading certain Erlide packages to avoid the conflict. In my original trial (above) I had let this alternative proceed, so earlier Erlide versions got installed. Then when I tried the Check for Updates, I hit the original conflict that I reported.
This time I DIDN'T let the "alternatives" go forward, and looked at the original error (below). So it looks like some kind of conflict in the packages that the update site is asking Eclipse to install in a from-scratch installation. Or at least Eclipse 4.5.2 is interpreting things that way. - Les
========================================
The installation cannot be completed as requested.


Cannot complete the install because of a conflicting dependency.
  Software being installed: Erlang headless support 0.23.1.201306270640 (org.erlide.headless.feature.group 0.23.1.201306270640)
  Software being installed: Erlang headless support 0.29.13.201509181435 (org.erlide.headless.feature.group 0.29.13.201509181435)
  Only one of the following can be installed at once: 
    Erlang headless support 0.29.13.201509181435 (org.erlide.headless.feature.jar 0.29.13.201509181435)
    Erlang headless support 0.23.1.201306270640 (org.erlide.headless.feature.jar 0.23.1.201306270640)
  Cannot satisfy dependency:
    From: Erlang headless support 0.23.1.201306270640 (org.erlide.headless.feature.group 0.23.1.201306270640)
    To: org.erlide.headless.feature.jar [0.23.1.201306270640]
  Cannot satisfy dependency:
    From: Erlang headless support 0.29.13.201509181435 (org.erlide.headless.feature.group 0.29.13.201509181435)
    To: org.erlide.headless.feature.jar [0.29.13.201509181435]

**Comment by gasserles** [comment]
PS I don't have any idea why the large boldface font is getting used when I post; sorry it looks that way.

**Comment by vladdu** [comment]
Do you uninstall even the headless feature? I think you should. I will investigate tomorrow.

**Comment by gasserles** [comment]
Yes, I uninstalled everything, and it all did appear to go away.  Thank you, Vlad. - Les

**Comment by vladdu** [comment]
The large typeface is because of the "=====" line which makes the previous paragraph a header.

**Comment by vladdu** [comment]
There are things I don't understand with the Eclipse updater, but since uninstalling and installing solves the issues, I don't think I should try too hard to solve this. Please reopen if you think otherwise.
